### PR TITLE
Fix freeotp ticket 54

### PR DESCRIPTION
**Pull request by tcely**
The off by one error reported at https://fedorahosted.org/freeotp/ticket/54 is likely caused by the subtraction that was on line 120.

### CODE REVIEW

**Comment by npmccallum** [comment]
I'm just trying to understand the history here before I merge a fix. I don't want to break anything.

The "-1" seems to have appeared in 7e05ee11ff86b939a2c409802151358d777f4417.

**Comment by tcely** [comment]
I don't know what you want me to tell you about the history. The commit message is not helpful and that change is in with a bunch of other unrelated changes.

The current behavior parsing of the counter value and subtracting one doesn't make any sense to me. It also causes the freeotp sequence to diverge from the reference implementation.

**Comment by npmccallum** [comment]
Sorry, my comment was intended for me. I hoped I had made that clear, but I haven't.

One thing you can do is check the test values of RFC 4226 and confirm that we are, indeed, off by one.

**Comment by npmccallum** [comment]
I confirmed the off-by-one error against RFC 4226. I pushed a fix.

**Pull request closed without merging**
